import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import React from 'react';
import axios from 'axios';
import { IGetCarDetailResponse } from '@/dto/car';
import DetailPage from '@/components/pages/detail-page';

interface DetailProps {
  carDetailData: IGetCarDetailResponse;
}

const Detail: NextPage<DetailProps> = ({ carDetailData }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DetailPage carDetailData={carDetailData} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const localhostUrl = process.env.LOCALHOST_URL;

  const res = await axios.post(`${localhostUrl}/api/getProductDetail`, {
    url: query.car
  });
  return {
    props: {
      carDetailData: res.data
    }
  };
};

export default Detail;
