import Head from "next/head";
import { GetServerSideProps } from "next";
import axios from "axios";

export default function Home() {
  const call = async () => {
    const response = await axios.post("/api/cron");
    console.log("response", response);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={call} style={{ width: "300px", height: "200px" }}>
        call
      </button>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      a: "a",
    },
  };
};
