import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import { prisma } from '../services/internal';
import React from 'react';
import { ICar } from '@/dto/car';
import Homepage from '@/components/pages/homepage';

interface HomeProps {
  cars: ICar[];
}

const Home: NextPage<HomeProps> = ({ cars }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage cars={cars} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const cars = await prisma.car.findMany();

  return {
    props: {
      cars: cars ?? []
    }
  };
};

export default Home;
